on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner.
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8 #install the python needed
      - name: install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: execute py script # run both the script get the latest data
        run: |
          python scrape_nbcnews.py
          python headline_fetch_nytimes.py
      
      - name: Commit changes 
        uses: EndBug/add-and-commit@v7
        with:
          author_name: drishyatm
          author_email: drishya.tm@qxf2.com
          message: 'Update CSV'
          add: '["nbc_news.csv","headline_nytimes.csv"]'
          


